### ISSUE TITLE
Packr 1.0.2 intermittently strips spaces with ruby 1.8.7 patch > p352

### ISSUE THREAD

**Issue by robd** [jcoglan/packr#3]
I just thought I'd document this issue here, but I recently upgraded to ruby 1.8.7 (2012-02-08 MBARI 8/0x6770 on patchlevel 358) [i686-darwin12.2.1], MBARI 0x6770, Ruby Enterprise Edition 2012.02

With the new version packr intermittently strips all spaces from javascript code (but not in strings). For example expected compressed output:

``` javascript
if(typeof YAHOO=="undefined"||!YAHOO){var YAHOO={}} ...
```

actual output:

``` javascript
if(typeofYAHOO=="undefined"||!YAHOO){varYAHOO={}} ...
```

This behaviour only occurs intermittently for certain runs of the ruby runtime. If the bug is happening, then all usages of Packr.pack will exhibit the behaviour while ruby is running. For another run of ruby, the bug doesn't happen at all.

I believe the problem lies with packr being dependant on hash ordering somewhere. Versions of ruby > 1.8.7 p352 return random hash orderings as per [this security fix](http://www.ruby-forum.com/topic/3312298).

Unfortunately this bug took me a long time to track down because I didn't initially realise it was related to a ruby upgrade which had happened a long time previously.

Anyway, I suggest this at least be documented somewhere and preferably fixed, though I realise 1.0.2 is very old now. Not sure if the problem manifests in newer versions.

**Comment by jcoglan** [comment]
I _believe_ hash ordering problems came up early-ish in Packr's development and were fixed by constructing parsers using an ordered syntax e.g. https://github.com/jcoglan/packr/blob/master/lib/packr/parser.rb#L10-L17. Are you able to update to a more recent release?

**Comment by robd** [comment]
I can't upgrade to a new release at the moment, because I don't have time to re qa everything on different browsers, but as you say, taking a quick look at the file you linked to, looks like you now ensure order through the [keys array in collection](https://github.com/jcoglan/packr/blob/master/lib/packr/base2/collection.rb#L9). I still don't really understand the problem I'm seeing, but I tried version 3.2.1 locally and I couldn't reproduce it, so probably OK to assume that an update fixed it at some point.

**Comment by jcoglan** [comment]
Closing this since it seems like a fixed problem in recent releases, and Ruby 1.8.7 is now EOL.
